apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "farm-dora-client.fullname" . }}
  labels:
    app: {{ include "farm-dora-client.name" . }}
    chart: {{ include "farm-dora-client.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "farm-dora-client.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "farm-dora-client.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "farm-dora-client.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment | quote }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
