replicaCount: 1

image:
  repository: chakisuk/farm-dora-buyer
  pullPolicy: Always
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8020

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    # - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 300m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8020
    initialDelaySeconds: 180
    periodSeconds: 10
    failureThreshold: 10
readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8020
    initialDelaySeconds: 180
    periodSeconds: 10
    failureThreshold: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes:
  - name: tmp-volume
    emptyDir: {}
volumeMounts:
  - name: tmp-volume
    mountPath: /tmp

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "prod"
  - name: key # jasypt.encryptor.password에서 사용하는 변수명과 일치
    valueFrom:
      secretKeyRef:
        name: farm-dora-secrets
        key: jasypt-key

environment: prod